/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        bg: "#F9F9F9",
        surface: "#FFFFFF",
        "surface-bright": "#FCF9F8",
        "surface-dim": "#DCD9D9",
        "surface-container-lowest": "#FFFFFF",
        "surface-container-low": "#F6F3F2",
        "surface-container": "#F0EDED",
        "surface-container-high": "#EAE7E7",
        "surface-container-highest": "#E5E2E1",
        "surface-variant": "#E5E2E1",
        "inverse-surface": "#313030",
        "inverse-on-surface": "#F3F0EF",
        text: "#1A1A1A",
        "text-muted": "#6B6B6B",
        "on-surface": "#1C1B1B",
        "on-surface-variant": "#46483C",
        primary: {
          DEFAULT: "#8A9A5B",
          hover: "#6E7A47",
          dark: "#56642B",
          tint: "#F0F2E8",
          container: "#8A9A5B",
          "on-container": "#253000",
        },
        "on-primary": "#FFFFFF",
        secondary: {
          DEFAULT: "#586333",
          container: "#DBE9AC",
          "on-container": "#5E6938",
        },
        tertiary: {
          DEFAULT: "#5C5F58",
          container: "#91948C",
          "on-container": "#2A2D27",
        },
        border: "#E5E5E5",
        outline: "#76786B",
        "outline-variant": "#C6C8B8",
        error: {
          DEFAULT: "#C0392B",
          container: "#FFDAD6",
          "on-container": "#93000A",
        },
        success: "#27AE60",
      },
      fontFamily: {
        headline: ['"Playfair Display"', "Georgia", "serif"],
        display: ['"Playfair Display"', "Georgia", "serif"],
        body: ["Inter", "system-ui", "sans-serif"],
        inter: ["Inter", "system-ui", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "8px",
        sm: "4px",
        md: "8px",
        lg: "12px",
        xl: "16px",
        pill: "9999px",
        full: "9999px",
      },
      boxShadow: {
        card: "0 4px 12px rgba(0, 0, 0, 0.06)",
        "card-hover": "0 12px 24px rgba(0, 0, 0, 0.08)",
        modal: "0 20px 40px rgba(0, 0, 0, 0.1)",
        subtle: "0 1px 4px rgba(0, 0, 0, 0.04)",
      },
      spacing: {
        gutter: "1.5rem",
        "gutter-desktop": "2rem",
        margin: "1.5rem",
        "margin-desktop": "5rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
      },
    },
  },
  plugins: [],
};
