export const productsData = [
  {
    name: 'Zig‘ir ko‘ylak',
    slug: 'zigir-koylak',
    description: '100% organik Yevropa zig‘iridan tikilgan hashamatli yozgi ko‘ylak. Nafas oluvchi, tabiiy yaltiroqlikka ega va kiygan sari yanada yumshab boruvchi mato. Tabiiy o‘simlik bo‘yoqlari bilan bo‘yalgan bo‘lib, teriga mutlaqo zararsizdir. Minimalistik erkin bichim sizga eng issiq kunlarda ham xushbo‘y salqinlik va o‘zgacha erkinlik baxsh etadi.',
    shortDescription: '100% Organik zig‘irdan tikilgan nafis yozgi ko‘ylak',
    categorySlug: 'ayollar',
    gender: 'ayollar',
    price: 1250000,
    compareAtPrice: 1500000,
    images: [
      {
        url: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800&auto=format&fit=crop&q=80',
        alt: 'Zig‘ir ko‘ylak - yashil',
        isPrimary: true,
      },
      {
        url: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800&auto=format&fit=crop&q=80',
        alt: 'Zig‘ir ko‘ylak - orqa ko‘rinish',
        isPrimary: false,
      },
      {
        url: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=800&auto=format&fit=crop&q=80',
        alt: 'Zig‘ir ko‘ylak - mato teksturasi',
        isPrimary: false,
      },
    ],
    variants: [
      { sku: 'ZK-GRN-XS', color: { name: 'Adaçayı Yashil', hex: '#8A9A5B' }, size: 'XS', stock: 12 },
      { sku: 'ZK-GRN-S', color: { name: 'Adaçayı Yashil', hex: '#8A9A5B' }, size: 'S', stock: 20 },
      { sku: 'ZK-GRN-M', color: { name: 'Adaçayı Yashil', hex: '#8A9A5B' }, size: 'M', stock: 25 },
      { sku: 'ZK-GRN-L', color: { name: 'Adaçayı Yashil', hex: '#8A9A5B' }, size: 'L', stock: 15 },
      { sku: 'ZK-GRN-XL', color: { name: 'Adaçayı Yashil', hex: '#8A9A5B' }, size: 'XL', stock: 0 },
      { sku: 'ZK-NAT-S', color: { name: 'Tabiiy Zig‘ir', hex: '#E2D8C3' }, size: 'S', stock: 18 },
      { sku: 'ZK-NAT-M', color: { name: 'Tabiiy Zig‘ir', hex: '#E2D8C3' }, size: 'M', stock: 22 },
      { sku: 'ZK-NAT-L', color: { name: 'Tabiiy Zig‘ir', hex: '#E2D8C3' }, size: 'L', stock: 14 },
    ],
    ecoBadge: '100% Organik zig‘ir',
    material: 'Organik zig‘ir',
    composition: '100% Sertifikatlangan Yevropa zig‘iri',
    careInstructions: [
      '30°C haroratda qo‘lda yoki nozik rejimda yuvilsin',
      'Xlorsiz ekologik vositalardan foydalaning',
      'Biroz namligida teskari tomonidan dazmollang',
    ],
    origin: 'Portugaliyada barqaror fabrikada tikilgan',
    certifications: ['GOTS', 'OEKO-TEX Standard 100', 'European Flax'],
    ecoImpact: {
      waterSavedLiters: 2400,
      co2SavedKg: 4.2,
      note: 'An‘anaviy paxtaga nisbatan 70% kam suv sarflangan',
    },
    tags: ['zig‘ir', 'yozgi', 'ko‘ylak', 'ekologik', 'ayollar'],
    isFeatured: true,
    isNewArrival: true,
    ratingAverage: 4.9,
    ratingCount: 28,
    soldCount: 94,
  },
  {
    name: 'Paxta futbolka',
    slug: 'paxta-futbolka',
    description: '100% organik O‘zbekiston paxtasidan ishlab chiqarilgan og‘ir vaznli (240 GSM) premium futbolka. Hech qanday sintetik qo‘shimchalarsiz, gipoallergen va nihoyatda chidamli. Kun davomida qulaylik va nafis minimalistik ko‘rinishni ta‘minlaydi.',
    shortDescription: '100% Organik O‘zbek paxtasidan tayyorlangan premium futbolka',
    categorySlug: 'ayollar',
    gender: 'uniseks',
    price: 480000,
    compareAtPrice: 580000,
    images: [
      {
        url: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&auto=format&fit=crop&q=80',
        alt: 'Oq paxta futbolka',
        isPrimary: true,
      },
      {
        url: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800&auto=format&fit=crop&q=80',
        alt: 'Qora paxta futbolka',
        isPrimary: false,
      },
    ],
    variants: [
      { sku: 'PF-WHT-S', color: { name: 'Sof Oq', hex: '#FFFFFF' }, size: 'S', stock: 35 },
      { sku: 'PF-WHT-M', color: { name: 'Sof Oq', hex: '#FFFFFF' }, size: 'M', stock: 50 },
      { sku: 'PF-WHT-L', color: { name: 'Sof Oq', hex: '#FFFFFF' }, size: 'L', stock: 40 },
      { sku: 'PF-WHT-XL', color: { name: 'Sof Oq', hex: '#FFFFFF' }, size: 'XL', stock: 20 },
      { sku: 'PF-SGE-M', color: { name: 'Adaçayı Yashil', hex: '#8A9A5B' }, size: 'M', stock: 25 },
      { sku: 'PF-SGE-L', color: { name: 'Adaçayı Yashil', hex: '#8A9A5B' }, size: 'L', stock: 30 },
    ],
    ecoBadge: '100% Organik paxta',
    material: 'Organik paxta',
    composition: '100% GOTS sertifikatiga ega organik paxta',
    careInstructions: ['40°C da mashinada yuvish mumkin', 'Past haroratda quritish tavsiya etiladi'],
    origin: 'O‘zbekiston, Toshkent',
    certifications: ['GOTS', 'Fair Trade Certified'],
    ecoImpact: {
      waterSavedLiters: 1100,
      co2SavedKg: 2.1,
      note: 'Pestitsidsiz organik dehqonchilik usulida yetishtirilgan paxta',
    },
    tags: ['futbolka', 'paxta', 'organik', 'asosiy'],
    isFeatured: true,
    isNewArrival: false,
    ratingAverage: 4.8,
    ratingCount: 42,
    soldCount: 168,
  },
  {
    name: 'Charm kamar',
    slug: 'charm-kamar',
    description: 'O‘simlik ekstraktlari yordamida oshlangan (vegetable-tanned) ekologik toza tabiiy charm kamar. Kimyoviy xrom moddalaridan to‘liq xoli. Qadimgi hunarmandchilik uslubida qo‘lda tikilgan va yillar o‘tib o‘ziga xos hashamatli patina tusini oladi.',
    shortDescription: 'O‘simlik usulida oshlangan ekologik charm kamar',
    categorySlug: 'aksessuarlar',
    gender: 'uniseks',
    price: 690000,
    compareAtPrice: 820000,
    images: [
      {
        url: 'https://images.unsplash.com/photo-1624222247344-550fb60583dc?w=800&auto=format&fit=crop&q=80',
        alt: 'Jigarrang tabiiy charm kamar',
        isPrimary: true,
      },
      {
        url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&auto=format&fit=crop&q=80',
        alt: 'Qora charm kamar',
        isPrimary: false,
      },
    ],
    variants: [
      { sku: 'CK-BRN-S', color: { name: 'Iliq Jigarrang', hex: '#6E473B' }, size: 'S', stock: 15 },
      { sku: 'CK-BRN-M', color: { name: 'Iliq Jigarrang', hex: '#6E473B' }, size: 'M', stock: 20 },
      { sku: 'CK-BRN-L', color: { name: 'Iliq Jigarrang', hex: '#6E473B' }, size: 'L', stock: 18 },
      { sku: 'CK-BLK-M', color: { name: 'Chuqur Qora', hex: '#1C1B1B' }, size: 'M', stock: 12 },
    ],
    ecoBadge: 'Xromsiz eko-charm',
    material: 'O‘simlik charmi',
    composition: '100% Tabiiy oshlangan charm, nikel bo‘lmagan guruch qisqich',
    careInstructions: ['Suv bilan uzoq kontaktga yo‘l qo‘ymang', 'Tabiiy mum bilan parvarishlang'],
    origin: 'Italiya, Toskana',
    certifications: ['Vegetable Tanned Leather Consortium'],
    ecoImpact: {
      waterSavedLiters: 800,
      co2SavedKg: 1.8,
      note: 'Kimyoviy og‘ir metallarsiz oshlash texnologiyasi',
    },
    tags: ['kamar', 'charm', 'aksessuar', 'klassik'],
    isFeatured: true,
    isNewArrival: false,
    ratingAverage: 5.0,
    ratingCount: 19,
    soldCount: 75,
  },
  {
    name: 'Organik paxta kardigan',
    slug: 'organik-paxta-kardigan',
    description: 'Qalin to‘qilgan, nihoyatda yumshoq organik paxta kardigani. Tabiiy yong‘oq qobig‘idan yasalgan tugmalar bilan bezatilgan. Salqin bahor va kuz oqshomlari uchun eng mukammal hamroh.',
    shortDescription: 'Tabiiy yong‘oq tugmali yumshoq organik kardigan',
    categorySlug: 'ayollar',
    gender: 'ayollar',
    price: 1100000,
    compareAtPrice: 1350000,
    images: [
      {
        url: 'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=800&auto=format&fit=crop&q=80',
        alt: 'Och sarg‘ish kardigan',
        isPrimary: true,
      },
    ],
    variants: [
      { sku: 'OPK-CRM-S', color: { name: 'Krem Tusli', hex: '#F6F3F2' }, size: 'S', stock: 14 },
      { sku: 'OPK-CRM-M', color: { name: 'Krem Tusli', hex: '#F6F3F2' }, size: 'M', stock: 20 },
      { sku: 'OPK-CRM-L', color: { name: 'Krem Tusli', hex: '#F6F3F2' }, size: 'L', stock: 10 },
      { sku: 'OPK-SGE-M', color: { name: 'Adaçayı', hex: '#8A9A5B' }, size: 'M', stock: 15 },
    ],
    ecoBadge: '100% Organik paxta',
    material: 'Organik to‘qima paxta',
    composition: '100% Organik sertifikatlangan paxta',
    careInstructions: ['Sovuq suvda qo‘lda yuvilsin', 'Gorizontal holda quritilsin'],
    origin: 'Portugaliya',
    certifications: ['GOTS', 'OEKO-TEX'],
    ecoImpact: {
      waterSavedLiters: 1950,
      co2SavedKg: 3.4,
      note: 'Bo‘yoqlarsiz tabiiy tola rangida',
    },
    tags: ['kardigan', 'paxta', 'trikotaj', 'ayollar'],
    isFeatured: true,
    isNewArrival: true,
    ratingAverage: 4.9,
    ratingCount: 31,
    soldCount: 88,
  },
  {
    name: 'Qayta ishlangan jun palto',
    slug: 'qayta-ishlangan-jun-palto',
    description: 'Qadimgi italyan fabrikalarida qayta ishlangan yuqori navli jundan tikilgan hashamatli qishki palto. Toza arxitekturaviy siluet, keng yoqa va qulay kamar. Tabiatga ziyon yetkazmasdan yuqori hashamat va iliqlik taqdim etadi.',
    shortDescription: 'Qayta ishlangan jundan tikilgan eksklyuziv qishki palto',
    categorySlug: 'ayollar',
    gender: 'ayollar',
    price: 3400000,
    compareAtPrice: 3900000,
    images: [
      {
        url: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=800&auto=format&fit=crop&q=80',
        alt: 'Kamel rangli jun palto',
        isPrimary: true,
      },
    ],
    variants: [
      { sku: 'QJP-CML-S', color: { name: 'Kamel', hex: '#C19A6B' }, size: 'S', stock: 8 },
      { sku: 'QJP-CML-M', color: { name: 'Kamel', hex: '#C19A6B' }, size: 'M', stock: 12 },
      { sku: 'QJP-CML-L', color: { name: 'Kamel', hex: '#C19A6B' }, size: 'L', stock: 6 },
    ],
    ecoBadge: 'Qayta ishlangan jun',
    material: 'Qayta ishlangan jun',
    composition: '80% Qayta ishlangan jun, 20% Organik paxta astar',
    careInstructions: ['Faqat ekologik quruq tozalash'],
    origin: 'Italiya',
    certifications: ['GRS (Global Recycled Standard)', 'OEKO-TEX'],
    ecoImpact: {
      waterSavedLiters: 4800,
      co2SavedKg: 12.5,
      note: '90% xomashyo qayta ishlangan jun tolalaridan olingan',
    },
    tags: ['palto', 'jun', 'qishki', 'premium'],
    isFeatured: true,
    isNewArrival: true,
    ratingAverage: 5.0,
    ratingCount: 16,
    soldCount: 42,
  },
  {
    name: 'Ipak ro‘mol',
    slug: 'ipak-romol',
    description: 'Marg‘ilon tabiiy ipakchilik an‘analari asosida tayyorlangan, qo‘lda bo‘yalgan hashamatli ipak sharf. Naqshlar ekologik toza o‘simlik bo‘yoqlari (anor po‘sti, isiriq, yong‘oq) yordamida tushirilgan. Har bir nusxa takrorlanmas san‘at asaridir.',
    shortDescription: 'Tabiiy bo‘yoqlar bilan qo‘lda ishlangan Marg‘ilon ipak ro‘moli',
    categorySlug: 'aksessuarlar',
    gender: 'ayollar',
    price: 850000,
    compareAtPrice: 990000,
    images: [
      {
        url: 'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=800&auto=format&fit=crop&q=80',
        alt: 'Ipak ro‘mol',
        isPrimary: true,
      },
    ],
    variants: [
      { sku: 'IR-SGE-STD', color: { name: 'Adaçayı Yashil', hex: '#8A9A5B' }, size: 'STANDART', stock: 25 },
      { sku: 'IR-IND-STD', color: { name: 'Nilgun Indigo', hex: '#3B4D61' }, size: 'STANDART', stock: 18 },
    ],
    ecoBadge: '100% Sof ipak',
    material: 'Marg‘ilon ipagi',
    composition: '100% Tabiiy pilladan olingan ipak',
    careInstructions: ['Faqat sovuq suvda nozik qo‘lda yuvish'],
    origin: 'O‘zbekiston, Marg‘ilon',
    certifications: ['Handmade Heritage', 'Eco-Dye Certified'],
    ecoImpact: {
      waterSavedLiters: 650,
      co2SavedKg: 1.2,
      note: '100% biologik parchalanuvchi va tabiiy bo‘yoqli',
    },
    tags: ['ipak', 'ro‘mol', 'sharf', 'an‘anaviy'],
    isFeatured: false,
    isNewArrival: true,
    ratingAverage: 4.9,
    ratingCount: 35,
    soldCount: 110,
  },
  {
    name: 'Zig‘ir shim',
    slug: 'zigir-shim',
    description: 'Keng bichimli, yuqori belli klassik zig‘ir shim. Bel qismida elastik tasma va bog‘ich mavjud. Kundalik qulaylik va rasmiy uslubni mukammal uyg‘unlashtiradi.',
    shortDescription: 'Erkin bichimli, yuqori belli tabiiy zig‘ir shim',
    categorySlug: 'ayollar',
    gender: 'ayollar',
    price: 950000,
    compareAtPrice: null,
    images: [
      {
        url: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800&auto=format&fit=crop&q=80',
        alt: 'Och kulrang zig‘ir shim',
        isPrimary: true,
      },
    ],
    variants: [
      { sku: 'ZS-NAT-S', color: { name: 'Tabiiy Qum', hex: '#DCD9D9' }, size: 'S', stock: 15 },
      { sku: 'ZS-NAT-M', color: { name: 'Tabiiy Qum', hex: '#DCD9D9' }, size: 'M', stock: 25 },
      { sku: 'ZS-NAT-L', color: { name: 'Tabiiy Qum', hex: '#DCD9D9' }, size: 'L', stock: 14 },
    ],
    ecoBadge: '100% Organik zig‘ir',
    material: 'Organik zig‘ir',
    composition: '100% Organik zig‘ir tolasi',
    careInstructions: ['30°C da yuvilsin', 'Past haroratda dazmollang'],
    origin: 'Litva',
    certifications: ['European Flax', 'OEKO-TEX'],
    ecoImpact: {
      waterSavedLiters: 1800,
      co2SavedKg: 2.8,
      note: 'Chidamlilik va uzoq umr ko‘rish kafolati',
    },
    tags: ['shim', 'zig‘ir', 'yozgi', 'ayollar'],
    isFeatured: false,
    isNewArrival: true,
    ratingAverage: 4.7,
    ratingCount: 22,
    soldCount: 65,
  },
  {
    name: 'Kanop ko‘ylak',
    slug: 'kanop-koylak',
    description: 'Kanop (hemp) tolasidan tikilgan barqaror moda durdonasi. Kanop matosi antibakterial xususiyatga ega bo‘lib, eng mustahkam tabiiy tolalardan biri hisoblanadi. Yuvilgan sayin yanada silliqlashadi.',
    shortDescription: 'Ekologik kanop tolasidan tikilgan uzoq muddatli ko‘ylak',
    categorySlug: 'ayollar',
    gender: 'ayollar',
    price: 1380000,
    compareAtPrice: 1600000,
    images: [
      {
        url: 'https://images.unsplash.com/photo-1502716119720-b23a93e5fe1b?w=800&auto=format&fit=crop&q=80',
        alt: 'Kanop ko‘ylak',
        isPrimary: true,
      },
    ],
    variants: [
      { sku: 'KK-OLV-S', color: { name: 'Zaytun', hex: '#586333' }, size: 'S', stock: 10 },
      { sku: 'KK-OLV-M', color: { name: 'Zaytun', hex: '#586333' }, size: 'M', stock: 16 },
      { sku: 'KK-OLV-L', color: { name: 'Zaytun', hex: '#586333' }, size: 'L', stock: 12 },
    ],
    ecoBadge: '100% Organik kanop',
    material: 'Tabiiy kanop tolasidir',
    composition: '100% Sanoat kanopi tolasi',
    careInstructions: ['30°C da nozik rejimda yuvish'],
    origin: 'Fransiya',
    certifications: ['GOTS', 'Global Organic Textile Standard'],
    ecoImpact: {
      waterSavedLiters: 3200,
      co2SavedKg: 5.1,
      note: 'Kanop yetishtirishda suv sarfi minimal va pestitsid talab etilmaydi',
    },
    tags: ['kanop', 'ko‘ylak', 'ekologik', 'ayollar'],
    isFeatured: true,
    isNewArrival: false,
    ratingAverage: 4.9,
    ratingCount: 20,
    soldCount: 52,
  },
  {
    name: 'Erkaklar zig‘ir ko‘ylagi',
    slug: 'erkaklar-zigir-koylagi',
    description: 'Klassik yoqali, erkin bichimli erkaklar zig‘ir ko‘ylagi. Fransuz zig‘iridan tayyorlangan, ofis yoki hordiq uchun birdek munosib hashamatli tanlov.',
    shortDescription: 'Klassik yoqali organik erkaklar zig‘ir ko‘ylagi',
    categorySlug: 'erkaklar',
    gender: 'erkaklar',
    price: 980000,
    compareAtPrice: 1150000,
    images: [
      {
        url: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800&auto=format&fit=crop&q=80',
        alt: 'Erkaklar ko‘k zig‘ir ko‘ylagi',
        isPrimary: true,
      },
    ],
    variants: [
      { sku: 'EZK-BLU-M', color: { name: 'Dengiz Ko‘ki', hex: '#46586C' }, size: 'M', stock: 20 },
      { sku: 'EZK-BLU-L', color: { name: 'Dengiz Ko‘ki', hex: '#46586C' }, size: 'L', stock: 25 },
      { sku: 'EZK-BLU-XL', color: { name: 'Dengiz Ko‘ki', hex: '#46586C' }, size: 'XL', stock: 15 },
      { sku: 'EZK-WHT-L', color: { name: 'Sof Oq', hex: '#FFFFFF' }, size: 'L', stock: 22 },
    ],
    ecoBadge: '100% Organik zig‘ir',
    material: 'Fransuz zig‘iri',
    composition: '100% Organik zig‘ir',
    careInstructions: ['30°C haroratda yuvish'],
    origin: 'Fransiya',
    certifications: ['European Flax', 'OEKO-TEX'],
    ecoImpact: {
      waterSavedLiters: 2100,
      co2SavedKg: 3.2,
      note: '75% kam suv va nol kimyoviy ishlov',
    },
    tags: ['erkaklar', 'ko‘ylak', 'zig‘ir'],
    isFeatured: true,
    isNewArrival: true,
    ratingAverage: 4.8,
    ratingCount: 39,
    soldCount: 132,
  },
  {
    name: 'Erkaklar organik paxta polo',
    slug: 'erkaklar-organik-paxta-polo',
    description: 'Pike to‘qilish uslubida tayyorlangan nafis organik polo futbolkasi. Qovurg‘ali yoqa va tabiiy chig‘anoq tugmalar bilan bezatilgan.',
    shortDescription: 'Premium pike to‘qimali organik paxta polo',
    categorySlug: 'erkaklar',
    gender: 'erkaklar',
    price: 620000,
    compareAtPrice: 750000,
    images: [
      {
        url: 'https://images.unsplash.com/photo-1618517351616-38fb9c5210c6?w=800&auto=format&fit=crop&q=80',
        alt: 'Erkaklar qora polo',
        isPrimary: true,
      },
    ],
    variants: [
      { sku: 'EOP-SGE-M', color: { name: 'Adaçayı', hex: '#8A9A5B' }, size: 'M', stock: 20 },
      { sku: 'EOP-SGE-L', color: { name: 'Adaçayı', hex: '#8A9A5B' }, size: 'L', stock: 28 },
      { sku: 'EOP-SGE-XL', color: { name: 'Adaçayı', hex: '#8A9A5B' }, size: 'XL', stock: 15 },
    ],
    ecoBadge: '100% Organik paxta',
    material: 'Organik paxta',
    composition: '100% GOTS organik paxta',
    careInstructions: ['Mashinada nozik yuvish'],
    origin: 'O‘zbekiston',
    certifications: ['GOTS', 'OEKO-TEX'],
    ecoImpact: {
      waterSavedLiters: 1350,
      co2SavedKg: 2.4,
      note: 'Tabiiy biologik to‘qima',
    },
    tags: ['polo', 'erkaklar', 'paxta'],
    isFeatured: false,
    isNewArrival: false,
    ratingAverage: 4.7,
    ratingCount: 27,
    soldCount: 89,
  },
  {
    name: 'Erkaklar jun pidjagi',
    slug: 'erkaklar-jun-pidjagi',
    description: 'Qayta ishlangan jun va zig‘ir aralashmasidan tayyorlangan zamonaviy dekonstruksiya qilingan pidjak. Yengil va o‘ta nafis ichki astar.',
    shortDescription: 'Dekonstruksiya qilingan zamonaviy eko-jun pidjak',
    categorySlug: 'erkaklar',
    gender: 'erkaklar',
    price: 2200000,
    compareAtPrice: 2600000,
    images: [
      {
        url: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&auto=format&fit=crop&q=80',
        alt: 'Erkaklar kulrang pidjagi',
        isPrimary: true,
      },
    ],
    variants: [
      { sku: 'EJP-GRY-M', color: { name: 'Tutun Kulrang', hex: '#5C5F58' }, size: 'M', stock: 8 },
      { sku: 'EJP-GRY-L', color: { name: 'Tutun Kulrang', hex: '#5C5F58' }, size: 'L', stock: 12 },
      { sku: 'EJP-GRY-XL', color: { name: 'Tutun Kulrang', hex: '#5C5F58' }, size: 'XL', stock: 6 },
    ],
    ecoBadge: 'Qayta ishlangan jun',
    material: 'Qayta ishlangan jun',
    composition: '70% Jun, 30% Zig‘ir',
    careInstructions: ['Quruq tozalash'],
    origin: 'Italiya',
    certifications: ['GRS', 'OEKO-TEX'],
    ecoImpact: {
      waterSavedLiters: 3800,
      co2SavedKg: 8.9,
      note: 'Resurslarni tejovchi to‘qima',
    },
    tags: ['pidjak', 'erkaklar', 'jun', 'klassik'],
    isFeatured: true,
    isNewArrival: false,
    ratingAverage: 4.9,
    ratingCount: 14,
    soldCount: 38,
  },
  {
    name: 'Erkaklar zig‘ir shimi',
    slug: 'erkaklar-zigir-shimi',
    description: 'To‘g‘ri bichimli, kundalik va rasmiy uchrashuvlarga mos erkaklar zig‘ir shimi. Chuqur cho‘ntaklar va mustahkamlangan choklar.',
    shortDescription: 'To‘g‘ri bichimli organik erkaklar zig‘ir shimi',
    categorySlug: 'erkaklar',
    gender: 'erkaklar',
    price: 890000,
    compareAtPrice: null,
    images: [
      {
        url: 'https://images.unsplash.com/photo-1479064555552-3ef4979f8908?w=800&auto=format&fit=crop&q=80',
        alt: 'Erkaklar zig‘ir shimi',
        isPrimary: true,
      },
    ],
    variants: [
      { sku: 'EZS-NAT-M', color: { name: 'Qum Rangi', hex: '#E5E2E1' }, size: 'M', stock: 18 },
      { sku: 'EZS-NAT-L', color: { name: 'Qum Rangi', hex: '#E5E2E1' }, size: 'L', stock: 22 },
      { sku: 'EZS-NAT-XL', color: { name: 'Qum Rangi', hex: '#E5E2E1' }, size: 'XL', stock: 14 },
    ],
    ecoBadge: '100% Organik zig‘ir',
    material: 'Organik zig‘ir',
    composition: '100% Fransuz zig‘iri',
    careInstructions: ['30°C da yuvish'],
    origin: 'Portugaliya',
    certifications: ['European Flax'],
    ecoImpact: {
      waterSavedLiters: 1900,
      co2SavedKg: 2.9,
      note: 'Tabiiy termoregulyatsiya xususiyati',
    },
    tags: ['shim', 'erkaklar', 'zig‘ir'],
    isFeatured: false,
    isNewArrival: true,
    ratingAverage: 4.8,
    ratingCount: 18,
    soldCount: 56,
  },
  {
    name: 'Organik zig‘ir sumka (Tote)',
    slug: 'organik-zigir-sumka-tote',
    description: 'Qalin va baquvvat organik zig‘ir matosidan tikilgan hashamatli tote sumkasi. Qulay keng dastalar va ichki xavfsiz cho‘ntak bilan ta‘minlangan.',
    shortDescription: 'Kundalik ehtiyojlar uchun mustahkam organik zig‘ir tote sumka',
    categorySlug: 'aksessuarlar',
    gender: 'uniseks',
    price: 390000,
    compareAtPrice: 480000,
    images: [
      {
        url: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&auto=format&fit=crop&q=80',
        alt: 'Zig‘ir tote sumka',
        isPrimary: true,
      },
    ],
    variants: [
      { sku: 'ZST-NAT-STD', color: { name: 'Tabiiy Zig‘ir', hex: '#E2D8C3' }, size: 'STANDART', stock: 40 },
      { sku: 'ZST-SGE-STD', color: { name: 'Adaçayı Yashil', hex: '#8A9A5B' }, size: 'STANDART', stock: 30 },
    ],
    ecoBadge: 'Nol chiqindi',
    material: 'Qalin organik zig‘ir',
    composition: '100% Og‘ir vaznli zig‘ir matosi',
    careInstructions: ['Qo‘lda sovuq suvda yuvish'],
    origin: 'O‘zbekiston, Samarqand',
    certifications: ['Zero Waste Certified', 'GOTS'],
    ecoImpact: {
      waterSavedLiters: 950,
      co2SavedKg: 1.5,
      note: 'Bir umrlik plastik xaltalarni almashtiruvchi barqaror mahsulot',
    },
    tags: ['sumka', 'tote', 'aksessuar'],
    isFeatured: true,
    isNewArrival: false,
    ratingAverage: 4.9,
    ratingCount: 45,
    soldCount: 195,
  },
  {
    name: 'Qayta ishlangan toladan ryukzak',
    slug: 'qayta-ishlangan-toladan-ryukzak',
    description: 'Okean plastiklari va qayta ishlangan poliesterdan tayyorlangan suv o‘tkazmaydigan shahar ryukzaki. 15 dyuymli noutbuk uchun himoyalangan maxsus bo‘lim mavjud.',
    shortDescription: 'Okean chiqindilaridan qayta ishlangan zamonaviy shahar ryukzaki',
    categorySlug: 'aksessuarlar',
    gender: 'uniseks',
    price: 890000,
    compareAtPrice: 1050000,
    images: [
      {
        url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&auto=format&fit=crop&q=80',
        alt: 'Eko ryukzak',
        isPrimary: true,
      },
    ],
    variants: [
      { sku: 'QIR-GRY-STD', color: { name: 'Qoramtir Kulrang', hex: '#313030' }, size: 'STANDART', stock: 20 },
      { sku: 'QIR-SGE-STD', color: { name: 'Adaçayı', hex: '#8A9A5B' }, size: 'STANDART', stock: 15 },
    ],
    ecoBadge: 'Ocean Bound Plastic',
    material: 'Qayta ishlangan rPET tola',
    composition: '100% Qayta ishlangan okean plastiklari',
    careInstructions: ['Nam mato bilan tozalash'],
    origin: 'Germaniya',
    certifications: ['Ocean Bound Plastic', 'GRS'],
    ecoImpact: {
      waterSavedLiters: 2600,
      co2SavedKg: 6.2,
      note: 'Har bir ryukzak uchun 35 ta plastik butilka qayta ishlangan',
    },
    tags: ['ryukzak', 'aksessuar', 'qayta ishlangan'],
    isFeatured: false,
    isNewArrival: true,
    ratingAverage: 4.8,
    ratingCount: 19,
    soldCount: 68,
  },
  {
    name: 'Tabiiy yog‘och quyosh ko‘zoynagi',
    slug: 'tabiiy-yogoch-quyosh-kozoynagi',
    description: 'Qayta tiklanadigan bambuk va yong‘oq daraxtidan qo‘lda tayyorlangan quyosh ko‘zoynagi. Qutblangan (polaroid) UV400 linzalar ko‘zni mukammal himoya qiladi.',
    shortDescription: 'Qo‘lda yasalgan bambuk va yong‘oq daraxtli ko‘zoynak',
    categorySlug: 'aksessuarlar',
    gender: 'uniseks',
    price: 520000,
    compareAtPrice: 650000,
    images: [
      {
        url: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800&auto=format&fit=crop&q=80',
        alt: 'Yog‘och ko‘zoynak',
        isPrimary: true,
      },
    ],
    variants: [
      { sku: 'TYK-WLN-STD', color: { name: 'Yong‘oq Yog‘ochi', hex: '#583D2A' }, size: 'STANDART', stock: 25 },
    ],
    ecoBadge: '100% FSC Yog‘och',
    material: 'Barqaror bambuk va yong‘oq daraxti',
    composition: 'FSC sertifikatli daraxt, TAC qutblangan linzalar',
    careInstructions: ['Mikrofibra mato bilan tozalang'],
    origin: 'Ispaniya',
    certifications: ['FSC Certified', 'CE UV400'],
    ecoImpact: {
      waterSavedLiters: 450,
      co2SavedKg: 0.9,
      note: 'Biologik parchalanuvchi tabiiy korpus',
    },
    tags: ['ko‘zoynak', 'aksessuar', 'yog‘och'],
    isFeatured: false,
    isNewArrival: false,
    ratingAverage: 5.0,
    ratingCount: 22,
    soldCount: 91,
  },
  {
    name: 'Bambuk tolasidan kofta',
    slug: 'bambuk-tolasidan-kofta',
    description: 'Bambuk tolasining ipakdek mayinligi va termoregulyatsiya xususiyatiga ega qulay kofta. Terlamaydi, hid qoldirmaydi va allergiyaga moyil teri uchun idealdir.',
    shortDescription: 'O‘ta mayin va gipoallergen bambuk tolasidan kofta',
    categorySlug: 'ayollar',
    gender: 'ayollar',
    price: 760000,
    compareAtPrice: 890000,
    images: [
      {
        url: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=800&auto=format&fit=crop&q=80',
        alt: 'Bambuk kofta',
        isPrimary: true,
      },
    ],
    variants: [
      { sku: 'BTK-IVR-S', color: { name: 'Fil Suyagi', hex: '#FCF9F8' }, size: 'S', stock: 15 },
      { sku: 'BTK-IVR-M', color: { name: 'Fil Suyagi', hex: '#FCF9F8' }, size: 'M', stock: 24 },
      { sku: 'BTK-IVR-L', color: { name: 'Fil Suyagi', hex: '#FCF9F8' }, size: 'L', stock: 18 },
    ],
    ecoBadge: '100% Organik bambuk',
    material: 'Bambuk tolasidir',
    composition: '95% Bambuk viskozasi, 5% Organik paxta',
    careInstructions: ['30°C da nozik rejim'],
    origin: 'Turkiya',
    certifications: ['OEKO-TEX Standard 100'],
    ecoImpact: {
      waterSavedLiters: 1600,
      co2SavedKg: 2.2,
      note: 'Bambuk daraxti eng tez tiklanuvchi tabiiy resursdir',
    },
    tags: ['bambuk', 'kofta', 'ayollar'],
    isFeatured: false,
    isNewArrival: true,
    ratingAverage: 4.8,
    ratingCount: 17,
    soldCount: 54,
  },
  {
    name: 'Organik jinsi shim',
    slug: 'organik-jinsi-shim',
    description: 'Zaharli bo‘yoqlarsiz va suvni 98% qayta ishlovchi yopiq tizimda ishlab chiqarilgan organik jinsi. Qulay to‘g‘ri bichim, o‘zgarmas klassik indigo tus.',
    shortDescription: 'Nol toksik moddasiz organik paxta jinsi shimi',
    categorySlug: 'ayollar',
    gender: 'ayollar',
    price: 1150000,
    compareAtPrice: 1390000,
    images: [
      {
        url: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=800&auto=format&fit=crop&q=80',
        alt: 'Klassik organik jinsi shim',
        isPrimary: true,
      },
    ],
    variants: [
      { sku: 'OJS-IND-S', color: { name: 'Klassik Indigo', hex: '#264057' }, size: 'S', stock: 14 },
      { sku: 'OJS-IND-M', color: { name: 'Klassik Indigo', hex: '#264057' }, size: 'M', stock: 22 },
      { sku: 'OJS-IND-L', color: { name: 'Klassik Indigo', hex: '#264057' }, size: 'L', stock: 16 },
    ],
    ecoBadge: 'Organik denim',
    material: 'Organik denim paxta',
    composition: '100% Organik paxta',
    careInstructions: ['Teskari qilib 30°C da yuvilsin'],
    origin: 'Italiya',
    certifications: ['Cradle to Cradle Certified', 'GOTS'],
    ecoImpact: {
      waterSavedLiters: 3500,
      co2SavedKg: 4.8,
      note: 'An‘anaviy jinsi ishlab chiqarishga qaraganda 85% suv tejalgan',
    },
    tags: ['jinsi', 'denim', 'ayollar'],
    isFeatured: true,
    isNewArrival: false,
    ratingAverage: 4.9,
    ratingCount: 38,
    soldCount: 114,
  },
  {
    name: 'Zig‘ir jaket',
    slug: 'zigir-jaket',
    description: 'Yengil yozgi astarli, nozik qirqimli ayollar zig‘ir jaketi. Ishbilarmonlik uchrashuvlari va oqshom sayrlari uchun nafis tashqi qatlam.',
    shortDescription: 'Nafis qirqimli yozgi ayollar zig‘ir jaketi',
    categorySlug: 'ayollar',
    gender: 'ayollar',
    price: 1450000,
    compareAtPrice: 1700000,
    images: [
      {
        url: 'https://images.unsplash.com/photo-1584273143981-41c073dfe8f8?w=800&auto=format&fit=crop&q=80',
        alt: 'Och jigar zig‘ir jaket',
        isPrimary: true,
      },
    ],
    variants: [
      { sku: 'ZJ-SGE-S', color: { name: 'Adaçayı Yashil', hex: '#8A9A5B' }, size: 'S', stock: 8 },
      { sku: 'ZJ-SGE-M', color: { name: 'Adaçayı Yashil', hex: '#8A9A5B' }, size: 'M', stock: 15 },
      { sku: 'ZJ-SGE-L', color: { name: 'Adaçayı Yashil', hex: '#8A9A5B' }, size: 'L', stock: 10 },
    ],
    ecoBadge: '100% Organik zig‘ir',
    material: 'Organik zig‘ir',
    composition: '100% Belgiyada to‘qilgan zig‘ir',
    careInstructions: ['Nozik quruq tozalash'],
    origin: 'Belgiya',
    certifications: ['Masters of Linen', 'OEKO-TEX'],
    ecoImpact: {
      waterSavedLiters: 2700,
      co2SavedKg: 3.9,
      note: 'Pestitsidsiz toza dehqonchilik mahsuloti',
    },
    tags: ['jaket', 'zig‘ir', 'ayollar', 'premium'],
    isFeatured: true,
    isNewArrival: true,
    ratingAverage: 5.0,
    ratingCount: 12,
    soldCount: 33,
  },
  {
    name: 'Tencel xalat-libos',
    slug: 'tencel-xalat-libos',
    description: 'Avstriya evkalipt daraxti tolasidan (TENCEL™ Lyocell) tayyorlangan oquvchan, ipakdek silliq xalat-libos. Qulay kamar va yon cho‘ntaklar bilan mukammallikka erishilgan.',
    shortDescription: 'Evkalipt tolasidan tayyorlangan nafis Tencel xalat-libos',
    categorySlug: 'ayollar',
    gender: 'ayollar',
    price: 1320000,
    compareAtPrice: 1550000,
    images: [
      {
        url: 'https://images.unsplash.com/photo-1568252542512-9fe8fe9c87bb?w=800&auto=format&fit=crop&q=80',
        alt: 'Tencel xalat libos',
        isPrimary: true,
      },
    ],
    variants: [
      { sku: 'TXL-RSE-S', color: { name: 'Changal Pushti', hex: '#D9C5B8' }, size: 'S', stock: 12 },
      { sku: 'TXL-RSE-M', color: { name: 'Changal Pushti', hex: '#D9C5B8' }, size: 'M', stock: 18 },
      { sku: 'TXL-RSE-L', color: { name: 'Changal Pushti', hex: '#D9C5B8' }, size: 'L', stock: 10 },
    ],
    ecoBadge: '100% TENCEL™ Lyocell',
    material: 'Tencel Lyocell',
    composition: '100% Lenzing Tencel',
    careInstructions: ['30°C da yuvish'],
    origin: 'Avstriya',
    certifications: ['OEKO-TEX', 'EU Ecolabel'],
    ecoImpact: {
      waterSavedLiters: 2900,
      co2SavedKg: 4.1,
      note: '99.5% erituvchilar qayta ishlatiladigan yopiq siklda tayyorlangan',
    },
    tags: ['tencel', 'libos', 'ayollar'],
    isFeatured: false,
    isNewArrival: false,
    ratingAverage: 4.9,
    ratingCount: 25,
    soldCount: 62,
  },
  {
    name: 'Kaşmir sviter',
    slug: 'kasmir-sviter',
    description: 'Mo‘g‘uliston tog‘ echkilarining tabiiy to‘kilgan tivitidan ehtiyotkorlik bilan yig‘ilgan hashamatli kaşmir sviter. Hech bir jonzotga ziyon yetkazilmagan.',
    shortDescription: 'Axloqiy usulda olingan 100% hashamatli kaşmir sviter',
    categorySlug: 'ayollar',
    gender: 'uniseks',
    price: 2800000,
    compareAtPrice: 3200000,
    images: [
      {
        url: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800&auto=format&fit=crop&q=80',
        alt: 'Kaşmir sviter',
        isPrimary: true,
      },
    ],
    variants: [
      { sku: 'KS-CRM-S', color: { name: 'Tabiiy Krem', hex: '#F0EDED' }, size: 'S', stock: 6 },
      { sku: 'KS-CRM-M', color: { name: 'Tabiiy Krem', hex: '#F0EDED' }, size: 'M', stock: 10 },
      { sku: 'KS-CRM-L', color: { name: 'Tabiiy Krem', hex: '#F0EDED' }, size: 'L', stock: 8 },
    ],
    ecoBadge: 'Axloqiy Kaşmir',
    material: 'Tabiiy kaşmir',
    composition: '100% Sertifikatlangan axloqiy kaşmir',
    careInstructions: ['Faqat qo‘lda sovuq suvda maxsus shampun bilan'],
    origin: 'Mo‘g‘uliston',
    certifications: ['Sustainable Cashmere Standard'],
    ecoImpact: {
      waterSavedLiters: 2200,
      co2SavedKg: 3.5,
      note: 'Yaylovlarga ziyon keltirmaydigan barqaror chorvachilik',
    },
    tags: ['kaşmir', 'sviter', 'premium'],
    isFeatured: true,
    isNewArrival: false,
    ratingAverage: 5.0,
    ratingCount: 29,
    soldCount: 71,
  },
  {
    name: 'Erkaklar eko-charm poyabzali',
    slug: 'erkaklar-eko-charm-poyabzali',
    description: 'Qayta ishlangan kauchuk taglik va o‘simlik usulida oshlangan charmdan qo‘lda tayyorlangan derbi poyabzali. Ortopedik qulaylik va beqiyos chidamlilik.',
    shortDescription: 'Qo‘lda tikilgan o‘simlik charmi va tabiiy kauchukli poyabzal',
    categorySlug: 'erkaklar',
    gender: 'erkaklar',
    price: 1750000,
    compareAtPrice: 2100000,
    images: [
      {
        url: 'https://images.unsplash.com/photo-1533867617858-e7b97e060509?w=800&auto=format&fit=crop&q=80',
        alt: 'Jigarrang poyabzal',
        isPrimary: true,
      },
    ],
    variants: [
      { sku: 'EEP-BRN-41', color: { name: 'Shokolad', hex: '#4A2F25' }, size: 'STANDART', stock: 8 },
      { sku: 'EEP-BRN-42', color: { name: 'Shokolad', hex: '#4A2F25' }, size: 'STANDART', stock: 12 },
      { sku: 'EEP-BRN-43', color: { name: 'Shokolad', hex: '#4A2F25' }, size: 'STANDART', stock: 10 },
    ],
    ecoBadge: 'Xromsiz charm',
    material: 'O‘simlik charmi',
    composition: '100% O‘simlik charmi, 100% Tabiiy kauchuk taglik',
    careInstructions: ['Tabiiy krem bilan tozalash'],
    origin: 'Portugaliya',
    certifications: ['Leather Working Group Gold'],
    ecoImpact: {
      waterSavedLiters: 1900,
      co2SavedKg: 4.5,
      note: 'Zaharli chiqindilarsiz mahalliy ishlab chiqarish',
    },
    tags: ['poyabzal', 'erkaklar', 'charm'],
    isFeatured: false,
    isNewArrival: false,
    ratingAverage: 4.8,
    ratingCount: 21,
    soldCount: 49,
  },
  {
    name: 'Qayta ishlangan shoyi ko‘ylak',
    slug: 'qayta-ishlangan-shoyi-koylak',
    description: 'Klassik kokteyl oqshomlari uchun qayta tiklangan hashamatli shoyi ko‘ylak. Yupqa tasmalar, oquvchan etak va nafis orqa o‘yiq.',
    shortDescription: 'Nafis oqshomlar uchun qayta ishlangan hashamatli shoyi ko‘ylak',
    categorySlug: 'chegirmalar',
    gender: 'ayollar',
    price: 1190000,
    compareAtPrice: 1790000,
    images: [
      {
        url: 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=800&auto=format&fit=crop&q=80',
        alt: 'Qora shoyi ko‘ylak',
        isPrimary: true,
      },
    ],
    variants: [
      { sku: 'QSK-BLK-S', color: { name: 'Mug‘om Qora', hex: '#1C1B1B' }, size: 'S', stock: 10 },
      { sku: 'QSK-BLK-M', color: { name: 'Mug‘om Qora', hex: '#1C1B1B' }, size: 'M', stock: 14 },
    ],
    ecoBadge: '33% Chegirma',
    material: 'Qayta tiklangan shoyi',
    composition: '100% Upcycled ipak',
    careInstructions: ['Nozik quruq tozalash'],
    origin: 'Italiya',
    certifications: ['GRS', 'Upcycled Certified'],
    ecoImpact: {
      waterSavedLiters: 3100,
      co2SavedKg: 5.6,
      note: 'Mavjud mato qoldiqlarini qayta hayotga qaytarish',
    },
    tags: ['chegirma', 'oqshom', 'shoyi', 'ayollar'],
    isFeatured: true,
    isNewArrival: false,
    ratingAverage: 4.9,
    ratingCount: 23,
    soldCount: 80,
  },
  {
    name: 'Organik zig‘ir bluzka',
    slug: 'organik-zigir-bluzka',
    description: 'V-simon yoqali, yengil burmali organik zig‘ir bluzkasi. Har qanday yubka yoki shim bilan mukammal mos tushadi.',
    shortDescription: 'V-yoqali nozik organik zig‘ir bluzka',
    categorySlug: 'chegirmalar',
    gender: 'ayollar',
    price: 680000,
    compareAtPrice: 920000,
    images: [
      {
        url: 'https://images.unsplash.com/photo-1551803091-e20673f15770?w=800&auto=format&fit=crop&q=80',
        alt: 'Krem zig‘ir bluzka',
        isPrimary: true,
      },
    ],
    variants: [
      { sku: 'OZB-CRM-S', color: { name: 'Krem', hex: '#F6F3F2' }, size: 'S', stock: 12 },
      { sku: 'OZB-CRM-M', color: { name: 'Krem', hex: '#F6F3F2' }, size: 'M', stock: 15 },
    ],
    ecoBadge: '26% Chegirma',
    material: 'Organik zig‘ir',
    composition: '100% Zig‘ir',
    careInstructions: ['30°C da yuvish'],
    origin: 'Litva',
    certifications: ['European Flax'],
    ecoImpact: {
      waterSavedLiters: 1700,
      co2SavedKg: 2.5,
      note: 'Tabiiy mato nafas oladi',
    },
    tags: ['bluzka', 'zig‘ir', 'chegirma'],
    isFeatured: false,
    isNewArrival: false,
    ratingAverage: 4.8,
    ratingCount: 15,
    soldCount: 60,
  },
  {
    name: 'Eko-shoyi sharf',
    slug: 'eko-shoyi-sharf',
    description: 'Yengil, havodor va ipakdek mayin eko-shoyi sharf. Har qanday libosga nafis urg‘u beradi.',
    shortDescription: 'Tabiiy o‘simlik bo‘yoqli shoyi sharf',
    categorySlug: 'chegirmalar',
    gender: 'uniseks',
    price: 350000,
    compareAtPrice: 500000,
    images: [
      {
        url: 'https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?w=800&auto=format&fit=crop&q=80',
        alt: 'Yashil shoyi sharf',
        isPrimary: true,
      },
    ],
    variants: [
      { sku: 'ESS-SGE-STD', color: { name: 'Adaçayı', hex: '#8A9A5B' }, size: 'STANDART', stock: 25 },
    ],
    ecoBadge: '30% Chegirma',
    material: 'Eko-shoyi',
    composition: '100% Organik ipak',
    careInstructions: ['Qo‘lda nozik yuvish'],
    origin: 'O‘zbekiston',
    certifications: ['OEKO-TEX'],
    ecoImpact: {
      waterSavedLiters: 600,
      co2SavedKg: 1.1,
      note: 'Nafis ekologik aksessuar',
    },
    tags: ['sharf', 'shoyi', 'chegirma'],
    isFeatured: false,
    isNewArrival: false,
    ratingAverage: 4.7,
    ratingCount: 11,
    soldCount: 45,
  },
];
